name: dotNetStandard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0.$GITHUB_RUN_NUMBER
      NAME: Walle.DeviceId
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build ./Walle.DeviceId/Walle.DeviceId.csproj /p:Version=${{env.VERSION}} -c Release  
    - name: Package
      run: dotnet pack ./Walle.DeviceId/Walle.DeviceId.csproj /p:Version=${{env.VERSION}} -c Release -o ./
    - name: Publish-microsoft-nuget
      run: dotnet nuget push ${{env.NAME}}.${{env.VERSION}}.nupkg --api-key ${{secrets.NUGET_MISAYA_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
 
